### ISSUE TITLE
Alternative ICs for AD7173 and OPA2111

### ISSUE THREAD

**Issue by mariobehling** [brain-duino/AD7173-Arduino#1]
[AD7173](https://www.mouser.sg/ProductDetail/Analog-Devices/AD7173-8BCPZ?qs=sGAEpiMZZMsrChSOYEGTCegWOOYfy6BbjXESgxq25zw%3d) IC is the heart of Neuro devices. But this IC costs nearly 17 USD. What are cheaper versions with similar or close capacities to this IC and evaluate the possibility of a replacement.

Similarly, [OPA2111](https://github.com/fossasia/neurolab-hardware/blob/master/docs/datasheets/OPA2111KP.pdf) is in a DIP package. It has pins that needs to be soldered differently than the SMD ICs. This will affect the manufacturing. Find an alternative to this IC which is in SMD packaging.

@CloudyPadmal already put up this question here some time ago as well: https://github.com/fossasia/neurolab-hardware/issues/55

What options do you see?

**Comment by silbo** [comment]
Not related to the code

**Comment by silbo** [comment]
Closing

**Comment by mkahata** [comment]
#1 is different one as this #2

https://github.com/brain-duino/AD7173-Arduino/pull/3￼
Adding CI build action (and fix usage of deprecated SPI APIs) by aentinger · Pull Request #3 · brain-duino/AD7173-Arduino
github.com
